name: cantinho_da_bru
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.10.0
  intl: ^0.18.1
  line_icons: ^2.0.1
  cloud_firestore: ^4.5.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_lints: ^2.0.0

########################################################

flutter:
  uses-material-design: true